MONGO:
  HOST: "127.0.0.1"
  PORT: 27017
  DATABASE: "soup_pvp"
  AUTH:
    ENABLED: false
    USERNAME: "user"
    PASSWORD: "pass"
    AUTH-DATABASE: "admin"

SERVER:
  SPAWN-LOCATION: 0.0, 64.0, 0.0
  SPAWN-SAFEZONE-MIN: 20.0, 92.0, -20.0
  SPAWN-SAFEZONE-MAX: -20.0, 32, 20.0